language: java

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jdk:
- oraclejdk8
script:
- mvn verify -Pit -B
after_success:
- mvn clean verify jacoco:report coveralls:report -Pcoveralls  -B
