SELECT DISTINCT *
FROM LINE_STOP t0, STATION t1 
WHERE t1.ENGLISHNAME = 'Liège-Guillemins'
AND t0.DATE = '2013-07-22'
AND t0.ARRIVAL_TIME_EXPECTED IS NOT NULL
AND t0.ARRIVAL_TIME_EXPECTED > '16:01:00' 
AND t1.ID = t0.STATION_ID
ORDER BY t0.ARRIVAL_TIME_EXPECTED ASC;