DROP TABLE  AAGT_STEP_EXECUTION_CONTEXT IF EXISTS;
DROP TABLE  AAGT_JOB_EXECUTION_CONTEXT IF EXISTS;
DROP TABLE  AAGT_STEP_EXECUTION IF EXISTS;
DROP TABLE  AAGT_JOB_EXECUTION IF EXISTS;
DROP TABLE  AAGT_JOB_PARAMS IF EXISTS;
DROP TABLE  AAGT_JOB_INSTANCE IF EXISTS;

DROP TABLE  AAGS_STEP_EXECUTION_SEQ IF EXISTS;
DROP TABLE  AAGS_JOB_EXECUTION_SEQ IF EXISTS;
DROP TABLE  AAGS_JOB_SEQ IF EXISTS;
DROP SEQUENCE  AAGS_INST_INCREMENT IF EXISTS;